// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package decisionlogs

import (
	"time"
)

type DecisionLog struct {
	DecisionID string    `json:"decision_id"`
	Path       string    `json:"path"`
	Input      string    `json:"input"`
	RevisionID *string   `json:"revision_id"`
	Result     string    `json:"result"`
	Timestamp  time.Time `json:"timestamp"`
}
