// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package decisionlogs

import (
	"database/sql"
	"time"
)

type DecisionLog struct {
	DecisionID string
	Path       string
	Input      sql.NullString
	Result     string
	Timestamp  time.Time
}
