// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package decisionlogs

import (
	"time"
)

type DecisionLog struct {
	DecisionID string
	Path       string
	Input      string
	Result     string
	Timestamp  time.Time
}
