// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package playgroundlogs

import (
	"context"
)

type Querier interface {
	CreatePlaygroundLog(ctx context.Context, arg CreatePlaygroundLogParams) (PlaygroundLog, error)
	GetPlaygroundLog(ctx context.Context, id string) (PlaygroundLog, error)
	ListPlaygroundlogs(ctx context.Context) ([]PlaygroundLog, error)
}

var _ Querier = (*Queries)(nil)
