// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package playgroundlogs

import (
	"time"
)

type PlaygroundLog struct {
	ID        string    `json:"id"`
	Input     string    `json:"input"`
	Policy    string    `json:"policy"`
	Result    string    `json:"result"`
	Coverage  string    `json:"coverage"`
	Timestamp time.Time `json:"timestamp"`
}
