// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package playgroundlogs

import (
	"time"
)

type PlaygroundLog struct {
	ID        string
	Input     string
	Policy    string
	Result    string
	Coverage  string
	Timestamp time.Time
}
